/**
 * Phase 4: publish Dev Signal briefing as a public GitHub Gist.
 */
export interface ScoredStory {
  id: string
  title: string
  url: string
  source: string | null
  summary: string | null
  category: string
  score: number
  why: string | null
  published_at: string | null
  scored_at: string
}

/** Avoid breaking markdown blocks when titles or rationales contain newlines. */
function oneLine(s: string): string {
  return s.replace(/\s+/g, ' ').trim()
}

function formatBriefingMarkdown(stories: ScoredStory[]): string {
  const date = new Date().toISOString().slice(0, 10)
  const lines: string[] = [
    `# Dev Signal Briefing — ${date}`,
    '',
    '> Autonomously generated by Dev Signal agent',
    '',
    '## Top Stories',
    '',
  ]

  if (stories.length === 0) {
    lines.push('*No stories in this briefing.*', '')
  } else {
    stories.forEach((story, index) => {
      const n = index + 1
      const title = oneLine(story.title) || '(untitled)'
      const url = story.url.trim() || '#'
      const source = story.source?.trim() ? story.source : 'unknown'
      const why = story.why?.trim() ? oneLine(story.why) : '_No rationale provided._'

      lines.push(
        `### ${n}. [${title}](${url})`,
        '',
        `**Source:** ${source} | **Score:** ${story.score}/10`,
        '',
        why,
        '',
        '---',
        ''
      )
    })
  }

  return lines.join('\n')
}

export async function publishBriefing(stories: ScoredStory[]): Promise<string | null> {
  const token = (process.env.GITHUB_TOKEN ?? '').trim()
  if (!token) {
    console.warn('[publishBriefing] GITHUB_TOKEN is not set; skipping gist publish')
    return null
  }

  try {
    const content = formatBriefingMarkdown(stories)
    const date = new Date().toISOString().slice(0, 10)
    const body = {
      description: `Dev Signal briefing ${date}`,
      public: true,
      files: {
        'devsignal-briefing.md': { content },
      },
    }

    const res = await fetch('https://api.github.com/gists', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
    })

    const text = await res.text()
    let parsed: unknown
    try {
      parsed = text ? JSON.parse(text) : null
    } catch {
      console.warn('[publishBriefing] gist response was not JSON', res.status, text.slice(0, 200))
      return null
    }

    if (!res.ok) {
      const msg =
        parsed && typeof parsed === 'object' && 'message' in parsed
          ? String((parsed as { message?: unknown }).message ?? '')
          : ''
      console.warn('[publishBriefing] GitHub API error', res.status, msg.slice(0, 300))
      return null
    }

    if (!parsed || typeof parsed !== 'object') {
      console.warn('[publishBriefing] unexpected gist response shape')
      return null
    }

    const htmlUrl = (parsed as { html_url?: unknown }).html_url
    if (typeof htmlUrl !== 'string' || !htmlUrl) {
      console.warn('[publishBriefing] gist response missing html_url')
      return null
    }

    return htmlUrl
  } catch (e) {
    console.warn('[publishBriefing] failed', e instanceof Error ? e.message : e)
    return null
  }
}
